# Converting Words into Features

* Initially the basic idea behind this is process the natural lanuage and feed the text format to the machince as a numeric type that machine can understand and process.

* We use One-Hot Encoding for dataset to convert text based data into numeric type and process that converted data using a neural network.

* By this method a lot of data have been feed as input for neural network, that have cost the computational power more and huge time to give a output.

* Because of these reasons, we follow a different method. Instead of feed the one-hot encoded data into neural network, we feed the <b>token index</b> of the data as the input of the neural network.

In [8]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator  
import torch

In [21]:
corpus = [
    "I love this product it is amazing",
    "This is the worst thing I ever bought",
    "Absolutely fantastic experience",
    "I hate this so much"
]

### Build Tokrnizer and Vocabulary

In [22]:
tokenizer = get_tokenizer("spacy", language="en_core_web_sm")

In [23]:
# define yield tokenizer function
def yield_tokens (data_iterate):
    for data in data_iterate:
        yield tokenizer(data)

In [24]:
# define iterator
data_iterate = iter(corpus)

In [25]:
# define vocab
vocab = build_vocab_from_iterator(yield_tokens(data_iterate))

In [ ]:
# define index of each token 
input_ids = lambda x: [torch.tensor(vocab(tokenizer(data_sample))) for data_sample in x]
index = input_ids(corpus)
print(index)

[tensor([ 0, 12,  2, 14, 11,  1,  5]), tensor([ 4,  1, 16, 18, 17,  0,  7,  6]), tensor([3, 9, 8]), tensor([ 0, 10,  2, 15, 13])]


In [28]:
# length of unique inputs(vocab)
vocab_len = len(vocab)
vocab_len

19

### Build Embedding Bag Layer

In [31]:
import torch.nn as nn

n_dimens = 3
n_embeddings = vocab_len
embedds = nn.Embedding(n_embeddings, n_dimens)
embedds


Embedding(19, 3)

In [34]:
index_0 = embedds(index[0])
index_0

tensor([[ 1.9231, -0.9310,  0.0799],
        [ 0.4802,  0.7076,  0.8138],
        [-0.8318,  0.6221, -1.7492],
        [-0.2386, -0.9096, -0.2121],
        [ 0.1543, -0.7264, -1.2424],
        [ 0.0690, -0.9315,  0.1884],
        [-0.0046, -0.6409,  0.9239]], grad_fn=<EmbeddingBackward0>)

## Offset

* We apply offset to recorganized the position of the starting point in each documents when all the documents are combined together

* So it provides efficient identification when handling a large dataset

In [35]:
index

[tensor([ 0, 12,  2, 14, 11,  1,  5]),
 tensor([ 4,  1, 16, 18, 17,  0,  7,  6]),
 tensor([3, 9, 8]),
 tensor([ 0, 10,  2, 15, 13])]

In [36]:
# combine all the index together
index_flat = torch.cat(index)
index_flat

tensor([ 0, 12,  2, 14, 11,  1,  5,  4,  1, 16, 18, 17,  0,  7,  6,  3,  9,  8,
         0, 10,  2, 15, 13])